# Generated by Django 3.1.3 on 2020-11-19 15:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storybook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
